services:
  postgresql:
    container_name: postgresql-billing-system
    image: postgres:16
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: billing-system-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgresql:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgresql: { }

networks:
  backend: { }