spring:
    application:
      name: billing-core

    datasource:
      url: jdbc:postgresql://localhost:5435/billing-system-db
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
      hikari:
        data-source-properties:
          stringtype: unspecified

    jpa:
      show-sql: true
      open-in-view: false

server:
  port: 8080