spring:
  application:
    name: billing-core

  datasource:
    url: jdbc:postgresql://localhost:5435/billing-system-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      data-source-properties:
        stringtype: unspecified

  jpa:
    show-sql: true
    open-in-view: false

  mail:
    host: ${EMAIL_HOST:smtp.yandex.ru}
    port: ${EMAIL_PORT:587}
    username: ${EMAIL}
    password: ${EMAIL_PASS}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
    default-encoding: UTF-8

server:
  port: 8080